#+TITLE: What Linux distro should I use? | kris.sh
#+OPTIONS: toc:nil num:nil author:nil timestamp:nil

#+BEGIN_EXPORT html
<h2>What Linux distro should I use?</h2>
<time datetime="2025-07-30T09:57:13-05:00">July 30, 2025</time> - <span class="tags">Linux</span>
#+END_EXPORT

This has become an incredibly difficult or impossible question to answer.

This post is inclined to be somewhat based on opinion, You have been warned.

If you want the short answer, pick something that looks interesting to you, try it out, and if you hate it? There are practically an infinite number of distros out there to try out next. (Though, I don't want to create a distrohopping addiction via this post.)

Everything sucks in one way or another? (foreshadowing) Well, you could always create your own or find something like [[https://kisscommunity.bvnf.space/][kiss linux]] to base off of and bootstrap your own thing, though I do think this is (slightly) unreasonable to expect from a new user.

** Some basic criteria for a new user
:PROPERTIES:
:CUSTOM_ID: some-basic-criteria-for-a-new-user
:END:
* Display server
:PROPERTIES:
:CUSTOM_ID: display-server
:END:
First and foremost, there are a lot of people with fairly "unusual" (these quotes are quite load-bearing) display setups, and despite whatever illogical thought process would lead one to disagree with this- Wayland support for a new user is going to be incredibly important.

In the context of distributions that are typically recommended to new users, [[https://linuxmint.com/][Linux Mint]] for example is one that usually comes up in the discussion, and with no hostility towards Linux Mint whatsoever, there is no stable/established Wayland support with any of their default desktop environment options.

Problems that may arise from X11 only environments would primarily include lack of support for mixed refresh rate displays without horrifically hacky workarounds that at best result in major amounts of screen tearing, due to the fact that both displays are more or less treated as one- running the higher refresh rate display at the framerate corresponding to the lower one, or vice versa (hence hacky workaround). This is a problem I personally fought with for years via my high (170/240hz) and low (60hz) refresh rate displays until I bought an AMD graphics card years ago and was finally able to move to Wayland permanently.

Another notable issue that does not matter much /to me/ personally, with X11 you are unable to use freesync at all if you have more than one display connected- even if they're identical.

Of course, scaling on X11 can also be a problem, among issues with modern display features in general.

The solution? Ask some questions about the hardware someone is using before making a suggestion- or just recommend something that provides a Wayland option that is relatively stable and established- such as an option that provides KDE or GNOME.

The primary concern here is that a user is going to install this, spend a bit trying to figure out why their monitors don't work correctly, and then bounce to something else or just flee back to Windows.

* Sensibly up to date software
:PROPERTIES:
:CUSTOM_ID: sensibly-up-to-date-software
:END:
When I suggest something "sensible" in this context- what I mean is generally not outdated enough to be a problem with newer hardware- which immediately rules out certain things that are (unreasonably) highly outdated- Debian for example, unless one chooses to use Debian Testing or pull specific things from backports so one is able to use newer hardware.

I think there's a happy medium here- my personal general distribution of choice, [[https://voidlinux.org/][Void]], /typically/ does not roll out "bleeding edge" software, but is also not generally "outdated." I tend to also be a fan of distributions that roll out a new release every 6 months or so, an example of a distro that does this (or sometimes, roughly this) would be [[https://fedoraproject.org/][Fedora]], though for various reasons (moderately annoying to pull Nvidia graphics drivers, weirdness around codecs, heavy-handed corporate involvement regardless of what people may suggest), I find it difficult to recommend. [[https://alpinelinux.org/][Alpine]] is another distribution that roughly does this, though quite difficult to recommend to newer users.

[[https://archlinux.org/][Arch]] would be a distro with *relatively* sanely up to date software, though I am personally not a fan of the "update just because there's an update" mentality around bleeding edge distributions.

* Software availability
:PROPERTIES:
:CUSTOM_ID: software-availability
:END:
While less of a concern compared to the days of old due to awesome solutions like [[https://flatpak.org/][flatpak]], software availability does matter in certain contexts. I imagine most users are allergic to packaging the things they need themselves, and should find something that has a lot of packages (preferably of decent quality) available.

I really seem to be talking about Arch a lot for someone who isn't a big fan, but I do think it is appropriate for newer users these days who aren't quite sure what they want.

Arch is pretty good at this due to the [[https://aur.archlinux.org/][AUR]], or Arch User Repository. The problem here is that random things on the AUR *cannot* be trusted. At minimum, you should be seeking packages that have a positive reputation and good comments, and preferably actually auditing packages you install yourself. There have been *many* cases of something malicious being uploaded to the AUR, and really the responsibility for that falls on the user being conscious of what they're doing.

Also, just to hammer that in, for all intents and purposes the AUR should be treated like a *public torrent tracker*, just with generic Arch packages as opposed to torrents. Oh, the days of keygen music and 12 toolbars suddenly appearing in Internet Explorer, along with the search engine changing on its own! Seriously though, /most/ packages are inclined to be fine but please be careful.

** Being responsible with recommending a distribution
:PROPERTIES:
:CUSTOM_ID: being-responsible-with-recommending-a-distribution
:END:
The point I am more or less trying to make here is that there isn't a good recommendation, and if you're asking the question of "What Linux distro should I use?" then generally, it probably doesn't matter much as you've yet to reach the point of developing opinions about certain software, but try not to deploy something that is going to be predictably problematic in one way or another. The key here is up to date software and a choice of what higher level software (desktop environments and the like) you interact with.

If suggesting distributions, try to keep in mind the experience a newer user may have with the thing you recommend *in their case, with their hardware and level of experience* may completely tarnish their opinion of the Linux ecosystem in general (though personally, I think modern Linux is a bit of a nightmare, blanket statement.)

More or less what I mean here is that new users are not going to stick around if they're dropped into the deep end immediately. Though, there is some value to this- given someone chooses to stick around and /actually/ learn Linux, they're bound to be a higher quality member of the community in general.

* So what distributions do YOU like, then?
:PROPERTIES:
:CUSTOM_ID: so-what-distributions-do-you-like-then
:END:
I get the sense that answering this question may lead to the (incredibly few) readers of this article interpreting my answer as a distro recommendation- *it isn't.*

Though, I know an answer is probably expected here, and reasonably so, so with the above in mind:

1. [[https://voidlinux.org/][Void]] - Has been my daily driver on both server and desktop for nearing 4 years as of the time of writing.

2. [[https://kisscommunity.bvnf.space/][Kiss]] - Uses a software stack I agree with by default assuming one uses the musl branch.

3. [[https://crux.nu/][Crux]] - I like the packaging system, and may only get slightly irritated with glibc.

Importantly, there are certain bits of software that I fundamentally disagree with- such as systemd. I definitely do not want spark some sort of illogical and ill-willed argument about systemd, the "religious" haters tend to completely miss the mark here. Fundamentally, if I don't want to use a specific piece of software (or in the case of systemd, a massive metapackage of random things), I should not have to. Opinions like this are what influence /my own/ distribution choices. And again because I know someone will ask- runit is my preferred init system / service manager, and a bunch of random other software to fill in the minor gaps for things that require systemd-isms- because that's sadly where the ecosystem has landed.

The above minor example of an opinion about what software goes into creating a Linux operating system is the type of opinion that will generally be developed over time via exposure, I wouldn't get /too/ caught up on specific details like this until you've gained some experience.

* Should your opinions influence my own?
:PROPERTIES:
:CUSTOM_ID: should-your-opinions-influence-my-own
:END:
No. Your own opinions are realistically the only ones that should matter to you. I am merely trying to bring up issues with the various approaches here.

** So what distro do you recommend I use?
:PROPERTIES:
:CUSTOM_ID: so-what-distro-do-you-recommend-i-use
:END:
This is the place this conversation usually leads to, and I know you are expecting some form of direct answer. In short- I have absolutely *no* idea. I do not know you, nor how you use your computer, nor what kind of hardware you have, nor your philosophical views which may influence your choice.

At best, I may be able to provide moderately random shots in the dark that may or may not stick, but do see the above "Being responsible with recommending a distribution."

Depending on someones level of experience with computers in general, I have a knack for recommending Arch installed via [[https://wiki.archlinux.org/title/Archinstall][archinstall]], as one of these "shots in the dark."

Despite the numerous issues with archinstall (mostly in terms of stability and questionable defaults), and despite the fact that it's not recommended by the Arch team (despite the fact that it's included in the official ISO by default? hello???), it may be a very quick and easy way for someone to get a system up that has up to date software, assuming they have someone to bounce questions off of while running the installer, and a practically endless level of software support, though I personally do not like Arch very much myself.

[[https://endeavouros.com/][EndeavourOS]] seems to be a valid shout, as it's relatively close to the Arch upstream and changes very few things that are bound to be minor adjustments to most users. The target here in my opinion would be people who look at a command line application (such as archinstall) and immediately decide it's too difficult. More or less, this will theoretically provide an Arch experience with "less effort."

** What distros (or type of distros) do you NOT recommend I use?
:PROPERTIES:
:CUSTOM_ID: what-distros-or-type-of-distros-do-you-not-recommend-i-use
:END:
- Things that don't have much of a reason to exist, generally. There are *tons* of Arch based distributions for example that do absolutely nothing notable, and at most just ship a desktop environment by default that may or may not have a preconfigured "rice." Most distros like this are pointless.

- There are also various distros with an incredibly negative history, things like [[https://manjaro.org/][Manjaro]] for example, do see [[https://manjarno.pages.dev/][manjarno]] for information about that specifically- it would be redundant for me to type out all of this information here.

- Incredibly small/niche distributions are sometimes really cool and are fine to use, and other times they're not. Before [[https://getsol.us/][Solus]] had died out, it was my absolute favorite "This just works out of the box!" type distribution, as it was also not the most bloated thing on earth. Nowadays, Solus /is/ apparently back, but the point here is that you may find yourself in a situation of needing to distrohop because the distro you chose has randomly ceased to exist, or it's no longer maintained very well or at all.

- Somewhat included in the above bullet point, things that are poorly maintained. [[https://system76.com/pop/][PopOS]] used to be the generic youtuber type suggestion, and at the time that may have been valid, but these days it is quite outdated and quite poorly maintained, as the effort has moved over to developing the Cosmic desktop environment for the time being. Even with major distributions like this, sometimes there are problems that are the same as or adjacent to the above bullet point.

* Arch is difficult to use! Muh elitism! I'm so good at computer because I installed Arch!
:PROPERTIES:
:CUSTOM_ID: arch-is-difficult-to-use-muh-elitism-im-so-good-at-computer-because-i-installed-arch
:END:
Stop. This is idiotic and intended to exclude people in a baseless manner. Once Arch has been installed, I personally refute the idea that it is somehow substantially more difficult to use than something else- install your software, use your software, update your system fairly regularly, ask questions, and I promise you'll have things figured out in no time. There is absolutely zero shame in asking questions- just don't be a [[https://meta.stackoverflow.com/a/258208][help vampire]], try to respect the nature of receiving free support at the expense of someone elses time in a chatroom on IRC or Discord, a forum somewhere, or whatever you may be using.

* All distributions are pretty much the same thing anyway, why does it matter?
:PROPERTIES:
:CUSTOM_ID: all-distributions-are-pretty-much-the-same-thing-anyway-why-does-it-matter
:END:
Quit it, or I'll get out the rolled up newspaper. This is highly incorrect- and may just seem this way if you only interact with Firefox and Steam on a daily basis and not much else.
